version: '3.5'

services:
  cpm-api:
    container_name: cpm-api
    environment:
      - PORT=3000
      - CHIA_LOGS=/chialogs
      - NODE_ENV=local
      - DEBUG=false
    volumes:
      - ./test/mock-logs:/chialogs # change ./test/mock-logs to your local chia folder
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000 # change first number to any port you wish to use on your system
    networks:
      - cpm-network

networks:
  cpm-network:
    name: cpm-network
